import torch
import torch.multiprocessing as mp
import time

# ==============================================================================
# Vmax Interview Exercise: Asymmetric Self-Play via Multiprocessing
# 
# Goal: Build a Teacher-Student pipeline using PyTorch mp.Queue.
# The Teacher generates tasks (environments).
# The Student pulls tasks, "solves" them, and sends the reward back.
# ==============================================================================

def teacher_worker(task_queue, reward_queue, num_tasks):
    """
    The Teacher generates environments/tasks and waits to see how hard they were.
    """
    print("[Teacher] Starting generation...")
    
    for i in range(num_tasks):
        # 1. Generate a dummy task (e.g., a tensor representing a maze or math problem)
        task_tensor = torch.randn(5, 5)
        
        # ==========================================
        # TODO 1: Push the task to the Student via the task_queue.
        # Ensure you include a task_id so you can track it!
        # ==========================================
        pass 
        
        # ==========================================
        # TODO 2: Pull the reward for this task from the reward_queue.
        # This simulates the "solver bottleneck". The Teacher must wait 
        # to see if the task was a "Goldilocks" difficulty.
        # ==========================================
        pass
        
        # print(f"[Teacher] Task {task_id} received reward: {reward}")

    # Signal the student that we are done
    task_queue.put("DONE")
    print("[Teacher] Finished.")

def student_worker(task_queue, reward_queue):
    """
    The Student acts as the 'solver', evaluating tasks generated by the Teacher.
    """
    print("[Student] Starting solver...")
    
    while True:
        # ==========================================
        # TODO 3: Pull a task from the task_queue.
        # If the task is the "DONE" signal, break the loop.
        # ==========================================
        pass
        
        # Simulate the slow "Solver in the Loop" (e.g., running SWE-bench)
        # print(f"[Student] Solving task {task_id}...")
        time.sleep(0.5) 
        
        # ==========================================
        # TODO 4: Calculate a dummy reward. 
        # (e.g., Just take the mean of the task_tensor and push it to the reward_queue).
        # ==========================================
        pass
        
    print("[Student] Finished.")

if __name__ == "__main__":
    # REQUIRED: PyTorch multiprocessing requires the 'spawn' context to share CUDA tensors safely.
    mp.set_start_method('spawn')
    
    num_tasks_to_generate = 10
    
    # ==========================================
    # TODO 5: Initialize two mp.Queue objects.
    # One for tasks going Teacher -> Student.
    # One for rewards going Student -> Teacher.
    # ==========================================
    task_queue = mp.Queue()   # this is teacher to student
    reward_queue = mp.Queue() # this is student to teacher

    # ==========================================
    # TODO 6: Instantiate and start the two mp.Process objects.
    # Process 1 runs teacher_worker. Process 2 runs student_worker.
    # ==========================================
    teacher_worker = mp.Process(target=***, args=(arg1, arg2))
    student_worker =     
    
    # ==========================================
    # TODO 7: Join the processes to ensure the main script waits for them to finish.
    # ==========================================
    
    print("[Main] All asynchronous self-play workers completed successfully.")